controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    broyden_controller:
      type: needle_controllers/BroydenController
      
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    real_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    sine_real_velocity_controller:
      type: galil_test_controllers/SineRealVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

broyden_controller:
  ros__parameters:
    joints:
      - horizontal_joint
      - insertion_joint
      - vertical_joint
    robot_base_link: world
    end_effector_link: tip
    interface_name: velocity

velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: velocity

real_velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: real_velocity

sine_real_velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: real_velocity
    joint_index: 0
    amplitude: 200.0
    frequency: 0.05
    offset: 0.0
    phase: 0.0
    duration: 0.0

position_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
