controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    real_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    sine_real_velocity_controller:
      type: galil_test_controllers/SineRealVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController
      
    mpc_controller:
      type: mp_needle_trajectory_controller/MpNeedleTrajectoryController
      
mpc_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: position
    max_velocity: 0.005

velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: velocity

real_velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: real_velocity

sine_real_velocity_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
    interface_name: real_velocity
    joint_index: 1
    amplitude: 2500.0
    frequency: 0.05
    offset: 0.0
    phase: 0.0
    duration: 0.0

position_controller:
  ros__parameters:
    joints:
      - insertion_joint
      - horizontal_joint
      - vertical_joint
      - needle_drive_joint
